### ISSUE TITLE
Errors preventing run in dev environment (latest master + npm updates)

### ISSUE THREAD

**Issue by kewilson** [adobe/cryptr#39]
## The problem

Fresh pull of master then npm audit fix to update to latest versions. Upon npm run dev the electron window shows black (no content) and the dev tools emits a bunch of errors, no content is ever shown in the electron window. The following errors are emitted by the dev tools plugin.

"Uncaught ReferenceError: Polymer is not defined" 

"Failed to load resource: net::ERR_FILE_NOT_FOUND"

"Uncaught (in promise) Error: Could not instantiate: ProductRegistryImpl.Registry"

"Electron Security Warning (Insecure Content-Security-Policy)"
"Electron[13369:68080] *** WARNING: Textured window <AtomNSWindow: 0x7fc179546ba0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead"

## Environment

* Cry ptr version (or git revision) that exhibits the issue: latest master + local updates to packages in package.json via npm outed suggestions.

* Desktop OS/version used to run Cryptr: mac mojave 10.14.3
* Vault version: ? - not linked up just trying to do first run of project to see the UI. The UI should load even without a vault backend setup/defined shouldn't it?

**Comment by jcrowthe** [comment]
@kewilson Thanks for the issue. This is somewhat expected as the new versions that npm audit recommend are not just bug/security fixes, but also include new features including potential deprecations of features. This is because npm audit cannot distinguish between the two -- it only know that "version 1.1.1 has a CVE while 2.0.0 does not, so I'm going to recommend 2.0.0".

Closing this issue but also scheduling (another) review of the fixes suggested by npm audit.
