### ISSUE TITLE
It's not possible to search specific secret using key in K/V secret engine

### ISSUE THREAD

**Issue by Neferites** [adobe/cryptr#53]
## The problem
It's not possible to search using key in K/V secret engine

## Environment

* Cryptr version (or git revision) that exhibits the issue:  0.4
* Desktop OS/version used to run Cryptr: Windows 2019 Version 1809
* Vault version: 1.5.4

## Details
When a secret is created with this K/V : 
`<my_username> : <my_username's_password>`
Cryptr is not able to search path / secret associate to <my_username>

## Steps to Reproduce
Create a secret in K/V v2, with key / value : 

- _my_username:my_password_
- _Search my_username_

**Secret path should be found**

**Comment by jcrowthe** [comment]
Closing old issue. Searching the contents of secrets is incredibly taxing on both the Vault server and the client, as every secret has to be downloaded and held in cache in order to be searched. As such, only secret _paths_ are searchable in Cryptr. A feature request to Hashicorp was opened a long time ago but has not received traction.
