### ISSUE TITLE
[Feature] support for moving folder

### ISSUE THREAD

**Issue by vickeyrihal1** [adobe/cryptr#63]
Can we have the support to move entire folder to some other location? At present the support is there for secrets.

**Comment by jcrowthe** [comment]
Hey Vickey, this is likely something better achieved as a scripted action taken outside of Cryptr. At this point it is unlikely to appear as a feature of Cryptr due to this and due to lack of dedicated time for writing new features for Cryptr. While this repo is not dead, it is in "maintenance mode" where only critical features and bugfixes are undertaken.
